### ISSUE TITLE
Alerts by Services

### ISSUE THREAD

**Issue by gpdamo** [junecastillote/Get-O365HealthReport#1]
The script works great.  One feature, I would like to see is if you can filter the alerts by service and or exclude\suppress alerts for a particular service.

Meaning, you only want to receive the alerts for maybe just Exchange Online and Skype for Business.  
Exclude the alerts for SharePoint, MS Teams and Office 365 Portal as an example.

**Comment by junecastillote** [comment]
Yes, that feature can be included in the next version. I'll consider it.

**Comment by junecastillote** [comment]
version 1.3 had been published, and now has the "exclude" feature.
Please see the readme file or go to https://www.lazyexchangeadmin.com/2018/10/shd365.html for the updated instructions on how to exclude workloads from the report

**Comment by gpdamo** [comment]
Version 1.3 worked perfectly, with the exclude feature added.   I currently have it implemented in the production environment with only the high visibility O365 apps sending monitoring notifications.  Great work June.

**Comment by junecastillote** [comment]
You're welcome. I'm glad it worked for you.
