### ISSUE TITLE
Error: The underlying connection was closed: An unexpected error occurred on a send

### ISSUE THREAD

**Issue by CDMN-GitHub** [junecastillote/Get-O365HealthReport#4]
Not sure if this is affecting everyone or just me but I found that recently the O365HealthReport script stopped working.

Running the script manually returned the error "The underlying connection was closed: An unexpected error occurred on a send"

Turns out the fix was to set the TLS version use by powershell at the time of execution by inserting the following code, in the script (prior to th efirst Invoke-RestMethod command)

Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12

**Comment by ehtobsemaj** [comment]
Can confirm, same issue and solution provided by CDMN-Github works.

Added:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12`

To line 199, directly below "try {" and script works again.
